#!/bin/bash

### Shell script for both making all the links and running th monte carlo

if [[ "$#" -eq "2" ]] 
then 
	Target=$1
	kin=$2
else 
	echo "Please enter Target " 
	read Target
	echo "Please enter kin # " 
	read kin
fi

if [ -f mcrun_info/input_"$Target"_kin"$kin".dat ] 
then
	echo "Linking the correct mc info file" 
	ln -sf mcrun_info/input_"$Target"_kin"$kin".dat input.dat
else
	echo "Please create input_"$Target"_kin"$kin".dat in /mcrun_info" 
	exit
fi

if [ -f datarun_info/run_"$Target"_kin"$kin".in ] 
then
	echo "Linking the correct data run file" 
	ln -sf datarun_info/run_"$Target"_kin"$kin".in reconmc.in
	
else
	echo "Please create run_"$Target"_kin"$kin".in in /datarun_info" 
	exit
fi

if [ -f ../phase_space_fall16/worksim/T2/"$Target"_kin"$kin".rzdat ] 
then
	echo "Linking the correct rzdat run file" 
	ln -sf ../phase_space_fall16/worksim/T2/"$Target"_kin"$kin".rzdat run.rzdat
else
	echo "Please generate the rzdat file needed"
	exit
fi


tgt="111sdasdas"
H3="H3"


if [ ${Target} == ${H3} ]
then
	tgt="T2"

elif [ ${Target} == "He3" ]
then
	tgt="HE3"
else 
	tgt=$Target
fi


if [ -e /home/jbane/tritium/T2_externals/OUT/marathon_kin${kin}_${tgt}.out ]
then
	echo "Making a link to the cross section table"
	ln -sf /home/jbane/tritium/T2_externals/OUT/marathon_kin${kin}_${tgt}.out rc94.dat
else
	echo "Please run the cross section code in T2_externals for "${tgt}"_kin"${kin}
	exit
fi

if [ ! -f "run.rzdat" ]
then
	echo "Exiting, somthing is wrong"
	#exit
fi

RUN=${Target}_kin${kin}

./recon_mc 
echo " "
echo "Just finish  $RUN!!!" 
echo " "
echo " Let's make those ntuples root files and move them to the proper places!!!"
echo " "
h2root "mcrun.rzdat"
echo " "
mv "mcrun.root" "rootfiles/mc$RUN.root"
echo " "
mv "mcrun.rzdat" "mc_rzdat/mc$RUN.rzdat"

