#!/bin/bash
set -x
### Shell script for both making all the links and running th monte carlo

cdir=$(pwd)
gendir=/home/jbane/halla_xem/phase_space_fall16
tabledir=~/tritium/T2_externals
weightdir=/home/jbane/halla_xem/weight_T2
doall=1
rc=1
redoall=1

if [[ "$#" -ge "0" ]] 
then 
	Target=$1
	if [[ ${Target} == "-h" || ${Target} == "help"  ]]
	then
		echo "--------HELP------"
		echo "You can run with the arguments"
		echo "Target kin# run# tgtID# "
		echo "You can also use the following tags"
		echo "OK to gen and make table(bool) and recreate already made root files(bool)"
		exit
	fi
fi

if [[ "$#" -ge "4" ]] 
then 
	Target=$1
	if [[ ${Target} == "-h" || ${Target} == "help"  ]]
	then
		echo "--------HELP------"
		echo "You can run with the arguments"
		echo "Target kin# run# tgtID# "
		echo "You can also use the following tags"
		echo "OK to gen and make table(bool) and recreate already made root files(bool)"
		exit
	fi

	kin=$2
	runnum=$3
	ID=$4
	if [[ "$#" -gt "4" ]]
	then
		doall=$5
	fi
	if [[ "$#" -gt "5" ]]
	then
		rc=$6
	fi
else 
	echo "Please enter Target " 
	read Target
	echo "Please enter run number"
	read runnum
	echo "Please enter kin # " 
	read kin
	echo "Please enter tgt ID (D2=2, H3=3,He3=4)"
	read ID
fi

if [ -e rootfiles/mc${runnum}.root ]
then
	if [ ${rc}==1 ]
	then
		rm -v rootfiles/mc${runnum}_*.root
	else
		echo "The mc root file exist. Do you want to recreate?"
		read ${rc}
		if [ ${rc} == "0" ]
		then
			exit
		else
			rm -v rootfiles/mc${runnum}_*.root
		fi	
	fi
fi


if [ -f mcrun_info/input.dat ] 
then
	echo "Linking the correct mc info file" 
	#ln -sf mcrun_info/input_"$Target"_kin"$kin".dat input.dat
else
	if (( ${doall} ))
	then
		echo "Making runinfo!!"
		#cd "${weightdir}/mcrun_info"
		#cp input.dat input_${Target}_kin${kin}.dat
		#ln -sf mcrun_info/input_"$Target"_kin"$kin".dat input.dat
		#cd ..
	else
		echo "Please create input_"$Target"_kin"$kin".dat in /mcrun_info" 
		exit
	fi
fi

if [ "$Target" == "D2" ]
then
        echo "D2"
        tarid=2
elif [ "$Target" == "H3" ]
then
        echo "H3"
        tarid=3

elif [ "$Target" == "He3" ]
then
        echo "He3"
        tarid=4

elif [ "$Target" == "carbon_foil" ]
then
        echo "foil"
        tarid=7

elif [ "$Target" == "optics" ]
then
        echo "optics"
        tarid=8
else
        echo "dummy"
        tarid=0
fi

if [ "$ID" == "10" ]
then
	ID=$tarid
fi

if [ -f datarun_info/run${runnum}.in ] 
then
	echo "Linking the correct data run file" 
	ln -sf datarun_info/run${runnum}.in reconmc.in
	
else	
	if (( ${doall} ))
	then
		echo "Making datrun_info"
		cd "${weightdir}/datarun_info"
		sh gen_datarun ${runnum} ${kin} ${ID}
		cd ${cdir}
		ln -sf datarun_info/run${runnum}.in reconmc.in 
	else
		echo "Please create run_${runnum}.in in /datarun_info" 
		exit
	fi
fi

if [[ ${ID} -lt 5 ]]
then

for x in $tarid 5 6
do
	ID=$x

	if [[ -e "${gendir}/worksim/${Target}_${runnum}_${ID}.rzdat" ]] 
	then
		if [ "${doall}" == 1 -a "${rc}" == 1 ] 
		then
			cd $gendir
			rm -v worksim/${Target}_${runnum}_${ID}.rzdat
			sh generate ${Target} ${runnum} ${ID} ${kin}
			cd $weightdir
			echo "Linking the correct rzdat run file" 
			ln -sf ../phase_space_fall16/worksim/${Target}_${runnum}_${ID}.rzdat run.rzdat
		else
			echo "Linking the correct rzdat run file" 
			ln -sf ../phase_space_fall16/worksim/${Target}_${runnum}_${ID}.rzdat run.rzdat
		fi
	else
		if [ "${doall}" == 1 ] 
		then
			cd $gendir
			sh generate ${Target} ${runnum} ${ID} ${kin}
			cd $weightdir
			echo "Linking the correct rzdat run file" 
			ln -sf ../phase_space_fall16/worksim/${Target}_${runnum}_${ID}.rzdat run.rzdat
		else
			echo "Please generate the rzdat file needed"
			exit
		fi
	
	fi


	tgt=$Target

	suffix[1]=""
	suffix[2]=""
	suffix[3]=""
	suffix[4]=""
	suffix[5]="_Alwalls_Up"
	suffix[6]="_Alwalls_Dn"


	modtgt="${tgt}${suffix[${tgtid}]}"

	if [ -e "/home/jbane/tritium/T2_externals/OUT/kin${kin}_${Target}_${ID}.out" -o ${redoall}=="0" ]
	then
		echo "Making a link to the cross section table"
		ln -sf /home/jbane/tritium/T2_externals/OUT/kin${kin}_${Target}_${ID}.out rc94.dat
	else
		if (( ${doall} ))
		then
			echo "Will make a cross section table for this run"
			cd $tabledir	
			sh CS ${tgt} ${kin} ${ID}
			cd $weightdir
			echo "Making a link to the cross section table"
			ln -sf /home/jbane/tritium/T2_externals/OUT/kin${kin}_${Target}_${ID}.out rc94.dat
		else
			echo "Make the table!! Try sh CS ${tgt}  ${kin} ${ID} "
			exit
		fi
	fi

	if [ ! -f "run.rzdat" ]
	then
		echo "Exiting, somthing is wrong"
		#exit
	fi

	RUN=${Target}_kin${kin}

	./recon_mc ${runnum} ${ID} 
	echo " "
	echo "Just finish  $RUN!!!" 
	echo " "
	echo " Let's make those ntuples root files and move them to the proper places!!!"
	echo " "
	h2root "mcrun.rzdat"
	echo " "
	mv "mcrun.root" "rootfiles/mc${runnum}_${ID}.root"
	echo " "
	mv "mcrun.rzdat" "mc_rzdat/mc${runnum}_${ID}.rzdat"
done


analyzer -b -l -q "merge.C(${runnum})"
#rm -v rootfiles/mc${runnum}_*.root

elif [[ ${ID} == 7 ]]
then
	
	tgt=C12
	if [ -e ../phase_space_fall16/worksim/carbon_foil_${runnum}_${ID}.rzdat -o ${rc}==1 ] 
	then
		if (( ${doall} )) 
		then
			cd $gendir
			sh generate carbon_foil ${runnum} ${ID} ${kin}
			cd $weightdir
			echo "Linking the correct rzdat run file" 
			ln -sf ../phase_space_fall16/worksim/carbon_foil_${runnum}_${ID}.rzdat run.rzdat
		else
			echo "Please generate the rzdat file needed"
			exit
		fi
	else
	
		echo "Linking the correct rzdat run file" 
		ln -sf ../phase_space_fall16/worksim/${Target}_${runnum}_${ID}.rzdat run.rzdat
	fi

	if [ -e "${tabledir}/OUT/kin${kin}_${tgt}_${ID}.out" -o ${redoall}=="0" ]
	then
		echo "Making a link to the cross section table"
		ln -sf ${tabledir}/OUT/kin${kin}_${tgt}_${ID}.out rc94.dat
	else
		if (( ${doall} ))
		then
			echo "Will make a cross section table for this run"
			cd $tabledir	
			sh CS ${tgt} ${kin} ${ID}
			cd $weightdir
			echo "Making a link to the cross section table"
			ln -sf ${tabledir}/OUT/kin${kin}_${tgt}_${ID}.out rc94.dat
		else
			echo "Make the table!! Try sh CS ${tgt}  ${kin} ${ID} "
			exit
		fi
	fi

	if [ ! -f "run.rzdat" ]
	then
		echo "Exiting, somthing is wrong"
		#exit
	fi

	RUN=${Target}_kin${kin}

	./recon_mc ${runnum} ${ID} 
	echo " "
	echo "Just finish  $RUN!!!" 
	echo " "
	echo " Let's make those ntuples root files and move them to the proper places!!!"
	echo " "
	h2root "mcrun.rzdat"
	echo " "
	mv "mcrun.root" "rootfiles/mc${runnum}.root"
	echo " "
	mv "mcrun.rzdat" "mc_rzdat/mc${runnum}_${ID}.rzdat"

elif [[ ${ID} == 8 ]]
then
	echo "optics not ready"
	exit
fi

